Navbar toggle: Fix IllegalArgumentException, fix potential memory leaks and dead working navbar frame
steps to replicate the issue: disable buttons navbar, enable it again, enable swipe up mode.

With the original toggle commit, we were just removing mNavigationBarView.
But mNavigationBar (the NavigationBarFragment) and the NavigationBarFrame that the first created
(see NavigationBarFragment.create - >
View navigationBarView = LayoutInflater.from(context).inflate(R.layout.navigation_bar_window, null)
navigation_bar_window is just the NavigationBarFrame)
were still floating around in the memory.
So after enabling navbar again, when the setSlippery call was triggered,
it was trying to do its stuff on the old -dead and not attached anymore- navbar frame:
final ViewGroup navbarView = ((ViewGroup) getParent())
(getParent returns the frame indeed).

To avoid this, when we toggle off the navbar, now we also kill the fragment
and the frame, so it will be created again when needed with all the proper views.

java.lang.IllegalArgumentException: View=com.android.systemui.statusbar.phone.NavigationBarFrame{f09c7b9 V.E...... ......ID 0,0-1440,161 #7f0a0228 app:id/navigation_bar_frame} not attached to window manager
stacktrace: java.lang.IllegalArgumentException: View=com.android.systemui.statusbar.phone.NavigationBarFrame{f09c7b9 V.E...... ......ID 0,0-1440,161 #7f0a0228 app:id/navigation_bar_frame} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:380)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:99)
	at com.android.systemui.statusbar.phone.NavigationBarView.setSlippery(NavigationBarView.java:838)
	at com.android.systemui.statusbar.phone.NavigationBarView.updateSlippery(NavigationBarView.java:818)
	at com.android.systemui.statusbar.phone.NavigationBarView.updateStates(NavigationBarView.java:811)
	at com.android.systemui.statusbar.phone.NavigationBarFragment$1.onInteractionFlagsChanged(NavigationBarFragment.java:200)
	at com.android.systemui.OverviewProxyService$1.lambda$setInteractionState$2(OverviewProxyService.java:142)
	at com.android.systemui.-$$Lambda$OverviewProxyService$1$OIMBB4z7B0rilnGoiEee2hjNc3M.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

- Change tuner string to match Dirty Tweaks

Change-Id: Ia2ff0b397f5e573106e5f5f683856033089e130a